server:
  port: 8082

spring:
  application:
    name: COMP3095_Assignment1
  jpa:
    show-sql: true   #print sql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: