server:
  port: 8082

spring:
  h2:
    console:
      path: /h2
      enabled: true
  application:
    name: COMP3095_Assignment1
  jpa:
    show-sql: true   #print sql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  thymeleaf:
    enabled: true
    encoding: utf-8
    prefix: classpath:/templates/
    cache: false
    mode: HTML
    suffix: .html